stages:
  - type: REPLACE
    from: ocean
    sampler:
      type: EXPRESSION
      expression: continentBorder(x, z)
    to:
      SELF: 1
      coast: 1
  - type: BORDER
    sampler:
      type: CONSTANT
    from: land
    replace: ocean
    to: coast
