stages:
  - type: REPLACE_LIST
    sampler:
      type: CELLULAR
      return: CellValue
      frequency: 1 / 1000 / ${customization.yml:variation-scale} / ${customization.yml:global-scale}
    
    default-from: ice-cap-flat
    default-to:
      - ICE_SPIKES: 1
    to:
        ice-cap:
          - SNOWY_MOUNTAINS: 2
        ice-cap-highlands:
          - SNOWY_MOUNTAINS: 2
        
        tundra-flat:
          - TUNDRA: 2
        tundra:
          - TUNDRA: 2
        tundra-highlands:
          - SNOWY_MOUNTAINS: 2
        
        polar-coast-flat:
          - FROZEN_BEACH: 2
        polar-coast:
          - SNOWY_SEA_CAVES: 2
        polar-coast-highlands:
          - SNOWY_SEA_CAVES: 2
  
        polar-mesa:
          - COLD_DESERT_MESA: 1
          
        polar-crater-lake:
          - todo: 1
          
        polar-extinct-volcano:
          - todo: 1
  
        polar-shallow-ocean:
          - FROZEN_OCEAN: 1
        polar-shallow-ocean-midlands:
          - FROZEN_OCEAN: 1
        polar-ocean:
          - FROZEN_OCEAN: 1
        polar-deep-ocean:
          - FROZEN_DEEP_OCEAN: 1
  
        boreal-hot-flat:
          - BIRCH_FOREST: 2
        boreal-hot:
          - BIRCH_FOREST: 2
        boreal-hot-highlands:
          - MOUNTAINS: 2
        
        boreal-warm-flat:
          - BIRCH_FOREST: 2
        boreal-warm:
          - DIVERSE_WOODLANDS: 2
          - REDWOOD_FOREST: 2
          - AUTUMNAL_FOREST: 3
          - TAIGA: 6
        boreal-warm-highlands:
          - MOUNTAINS: 2
          - AUTUMNAL_FOREST_HILLS: 3
          - FLOWERING_AUTUMNAL_FOREST_HILLS: 1

        boreal-cold-flat:
          - TAIGA: 2
        boreal-cold:
          - TAIGA: 2
        boreal-cold-highlands:
          - MOUNTAINS: 2
      
        boreal-snowy-flat:
          - SNOWY_MEADOW: 2
        boreal-snowy:
          - SNOWY_MEADOW: 2
        boreal-snowy-highlands:
          - SNOWY_MOUNTAINS: 2
        
        boreal-hot-dry-flat:
          - BIRCH_FOREST: 2
        boreal-hot-dry:
          - TAIGA: 2
        boreal-hot-dry-highlands:
          - MOUNTAINS: 2

        boreal-warm-dry-flat:
          - TAIGA: 2
        boreal-warm-dry:
          - TAIGA: 2
        boreal-warm-dry-highlands:
          - MOUNTAINS: 2

        boreal-cold-dry-flat:
          - TAIGA: 2
        boreal-cold-dry:
          - TAIGA: 2
        boreal-cold-dry-highlands:
          - SNOWY_MOUNTAINS: 2

        boreal-snowy-dry-flat:
          - SNOWY_MEADOW: 2
        boreal-snowy-dry:
          - SNOWY_MEADOW: 2
        boreal-snowy-dry-highlands:
          - SNOWY_MOUNTAINS: 2

        boreal-coast-flat:
          - ROCKY_ARCHIPELAGO: 6
          - SHALE_BEACH: 2
        boreal-coast:
          - ROCKY_SEA_CAVES: 2
        boreal-coast-highlands:
          - ROCKY_SEA_CAVES: 2
  
        boreal-mesa:
          - BOREAL_MESA: 1
        
        boreal-crater-lake:
          - todo: 1
        
        boreal-extinct-volcano:
          - todo: 1
  
        boreal-shallow-ocean:
          - COLD_OCEAN: 1
          - KELP_FOREST: 1
        boreal-shallow-ocean-midlands:
          - COLD_OCEAN: 1
        boreal-ocean:
          - COLD_OCEAN: 1
        boreal-deep-ocean:
          - COLD_DEEP_OCEAN: 1
  
        temperate-hot-dry-flat:
          - PALM_FOREST: 2
          - CHAPARRAL: 2
          - MOORLAND: 2
        temperate-hot-dry:
          - CHAPARRAL: 2
          - MOORLAND: 2
        temperate-hot-dry-highlands:
          - DRY_TEMPERATE_MOUNTAINS: 2
          - DRY_TEMPERATE_WHITE_MOUNTAINS: 2

        temperate-warm-dry-flat:
          - PALM_FOREST: 2
          - CHAPARRAL: 2
          - MOORLAND: 2
        temperate-warm-dry:
          - CHAPARRAL: 2
          - MOORLAND: 2
        temperate-warm-dry-highlands:
          - DRY_TEMPERATE_MOUNTAINS: 2
          - DRY_TEMPERATE_WHITE_MOUNTAINS: 2

        temperate-hot-flat:
          - GRASSLAND: 2
          - ALIEN_MARSH: 1
          - AUTUMNAL_FLATS: 2
        temperate-hot:
          - WOODED_BUTTES: 2
          - TEMPERATE_OVERPASS: 2
        temperate-hot-highlands:
          - HIGHLANDS: 2
          - TEMPERATE_ALPHA_MOUNTAINS: 2
          - TEMPERATE_MOUNTAINS: 2

        temperate-warm-flat:
          - FLOWERING_FOREST: 2
          - EVERGREEN_FOREST: 2
          - OAK_FOREST: 2
          - DARK_FOREST: 2
          - SAKURA_GROVE: 2
          - WOODED_BUTTES: 2
        temperate-warm:
          - FLOWERING_FOREST: 2
          - EVERGREEN_FOREST: 2
          - OAK_FOREST: 2
          - DARK_FOREST: 2
          - SAKURA_GROVE: 2
          - WOODED_BUTTES: 2
        temperate-warm-highlands:
          - HIGHLANDS: 2
          - TEMPERATE_ALPHA_MOUNTAINS: 2
          - TEMPERATE_MOUNTAINS: 2

        temperate-cold-flat:
          - FLOWERING_FOREST: 2
          - EVERGREEN_FOREST: 2
          - OAK_FOREST: 2
          - DARK_FOREST: 2
          - SAKURA_GROVE: 2
          - WOODED_BUTTES: 2
        temperate-cold:
          - FLOWERING_FOREST: 2
          - EVERGREEN_FOREST: 2
          - OAK_FOREST: 2
          - DARK_FOREST: 2
          - SAKURA_GROVE: 2
          - WOODED_BUTTES: 2
        temperate-cold-highlands:
          - HIGHLANDS: 2
          - TEMPERATE_ALPHA_MOUNTAINS: 2
          - TEMPERATE_MOUNTAINS: 2

        temperate-coast-flat:
          - BEACH: 2
        temperate-coast:
          - TEMPERATE_SEA_ARCHES: 2
        temperate-coast-highlands:
          - TEMPERATE_SEA_ARCHES: 2

        temperate-mesa:
          - TEMPERATE_MESA: 1
        
        temperate-crater-lake:
          - TEMPERATE_CRATER_LAKE: 1
        
        temperate-extinct-volcano:
          - TEMPERATE_EXTINCT_VOLCANO: 1

        temperate-shallow-ocean:
          - OCEAN: 1
          - KELP_FOREST: 1
          - SEAGRASS_MEADOW: 1
        temperate-shallow-ocean-midlands:
          - ROCKY_SHALLOW_OCEAN: 1
        temperate-ocean:
          - OCEAN: 1
        temperate-deep-ocean:
          - DEEP_OCEAN: 1

        # Red hot desert
        hot-desert-flat-red:
          - ARID_SPIKES: 1
          - BADLANDS: 1
          - BADLANDS_BUTTES: 1
          - RED_DESERT: 1
          - SALT_FLATS: 1
        hot-desert-red:
          - ARID_SPIKES: 1
          - BADLANDS: 1
          - BADLANDS_BUTTES: 1
          - RED_DESERT: 1
        hot-desert-highlands-red:
          - ARID_SPIKES: 1
          - BADLANDS: 1
          - BADLANDS_BUTTES: 1
      
        # Orange hot desert
        hot-desert-flat-orange:
          - ORANGE_DESERT: 2
          - SALT_FLATS: 1
        hot-desert-orange:
          - ORANGE_DESERT: 1
        hot-desert-highlands-orange: 
          - ORANGE_DESERT: 1

        # White hot desert
        hot-desert-flat-white:
          - DESERT: 3
          - PEARLESCENT_DESERT: 1
          - SALT_FLATS: 1
          - DESERT_SAVANNA_OVERHANGS: 2
        hot-desert-white:
          - DESERT: 1
          - DESERT_PILLARS: 1
          - DESERT_SPIKES: 1
          - DESERT_SPIKES_GOLD: 1
          - DESERT_TERRACES: 1
          - JUNGLE_DESERT_TERRACES: 2
          - ROCKY_DESERT: 1
          - PEARLESCENT_DESERT: 1
        hot-desert-highlands-white:
          - DESERT_PILLARS: 1
          - DESERT_SPIKES: 1
          - DESERT_SPIKES_GOLD: 1
          - DESERT_TERRACES: 1
          - ROCKY_DESERT: 1
          - JUNGLE_DESERT_TERRACES: 2
          - PEARLESCENT_DESERT: 1

        # Red hot steppe
        hot-steppe-flat-red:
          - ARID_SPIKES: 1
        hot-steppe-red:
          - ARID_SPIKES: 1
        hot-steppe-highlands-red:
          - ARID_SPIKES: 1

        # Orange hot steppe
        hot-steppe-flat-orange:
          - ARID_SPIKES: 1
        hot-steppe-orange:
          - ARID_SPIKES: 1
        hot-steppe-highlands-orange:
          - ARID_SPIKES: 1

        # White hot steppe
        hot-steppe-flat-white:
          - XERIC_SHRUBLAND: 1
          - DESERT_SAVANNA_OVERHANGS: 2
        hot-steppe-white:
          - XERIC_SHRUBLAND: 1
        hot-steppe-highlands-white:
          - XERIC_MOUNTAINS: 1

        temperate-steppe-flat:
          - GREAT_STEPPE: 1
        temperate-steppe:
          - GREAT_STEPPE: 1
        temperate-steppe-highlands:
          - GREAT_STEPPE: 1

        cold-desert-flat:
          - SALT_FLATS: 1
        cold-desert:
          - SNOWY_DUNES: 1
          - SNOWY_BADLANDS: 1
        cold-desert-highlands:
          - SNOWY_MOUNTAINS: 1
          - SNOWY_BADLANDS: 1

        cold-steppe-flat:
          - GREAT_STEPPE: 1
        cold-steppe:
          - GREAT_STEPPE: 1
        cold-steppe-highlands:
          - GREAT_STEPPE: 1

        cold-desert-mesa:
          - COLD_DESERT_MESA: 1
        
        cold-desert-crater-lake:
          - todo: 1
        
        cold-desert-extinct-volcano:
          - todo: 1

        arid-coast-flat:
          - BEACH: 1
        arid-coast:
          - SANDSTONE_ARCHIPELAGO: 1
        arid-coast-highlands:
          - TERRACOTTA_SEA_CAVES: 1

        desert-mesa:
          - DESERT_MESA: 1
        
        desert-crater-lake:
          - todo: 1
        
        desert-extinct-volcano:
          - todo: 1

        tropical-rainforest-flat:
          - BAMBOO_JUNGLE: 2
          - JUNGLE: 2
          - ROCKY_JUNGLE: 2
        tropical-rainforest:
          - BAMBOO_JUNGLE: 2
          - BAMBOO_PONDS: 2
          - JUNGLE: 2
          - ROCKY_JUNGLE: 2
        tropical-rainforest-highlands:
          - OVERGROWN_CLIFFS: 2

        tropical-monsoon-flat:
          - DRY_FOREST: 2
          - MONSOON_FOREST: 2
        tropical-monsoon:
          - DRY_FOREST: 2
          - MONSOON_FOREST: 2
        tropical-monsoon-highlands:
          - DRY_FOREST: 2
          - MONSOON_FOREST: 2

        tropical-savanna-dry-flat:
          - GRASS_SAVANNA: 2
          - SAVANNA: 2
        tropical-savanna-dry:
          - GRASS_SAVANNA: 2
          - SAVANNA: 2
        tropical-savanna-dry-highlands:
          - SAVANNA_OVERHANGS: 2

        tropical-savanna-wet-flat:
          - WET_SAVANNA: 1
        tropical-savanna-wet:
          - WET_SAVANNA: 1
        tropical-savanna-wet-highlands:
          - SAVANNA_OVERHANGS: 1
          - DESERT_SAVANNA_OVERHANGS: 2

        tropical-coast-flat:
          - PALM_BEACH: 2
          - MANGROVE_SWAMP: 2
        tropical-coast: LUSH_SEA_CAVES
        tropical-coast-highlands: LUSH_SEA_CAVES

        tropical-mesa:
          - TROPICAL_MESA: 2
        
        tropical-crater-lake:
          - todo: 1
        
        tropical-extinct-volcano:
          - todo: 1

        hot-shallow-ocean: 
          - TROPICAL_OCEAN: 1
          - SEAGRASS_MEADOW: 1
        hot-shallow-ocean-midlands:
          - TROPICAL_OCEAN: 1
          - SEAGRASS_MEADOW: 1
        hot-ocean: TROPICAL_OCEAN
        hot-deep-ocean: TROPICAL_DEEP_OCEAN
